apiVersion: v1
kind: Pod
metadata:
  name: client
spec:
  containers:
  - image: yauritux/busybox-curl
    command:
      - sleep
      - "7200"
    imagePullPolicy: IfNotPresent
    name: client
  restartPolicy: Always