#!/bin/bash

set -eu

SCRIPTDIR=$( dirname "${BASH_SOURCE[0]}" )

NAME=$1
echo "Create user $NAME"

./$SCRIPTDIR/generate_pvc_resource $NAME
kubectl apply -f ./$SCRIPTDIR/pvc-$NAME.yaml
./$SCRIPTDIR/generate_user_resources $NAME
kubectl apply -f ./$SCRIPTDIR/easyfit-$NAME.yaml
