---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: workshop
  name: xxx
spec:
  selector:
    matchLabels:
      app: xxx
  replicas: 1
  template:
    metadata:
      labels:
        app: xxx
    spec:
      containers:
      - name: easyfit
        image: c0d1ngm0nk3y/easyfit
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: xxx-service
  namespace: workshop
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: xxx
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: xxx-ingress
  namespace: workshop
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: 60s
spec:
  rules:
  - host: xxx.ingress.k8s.d050893.shoot.canary.k8s-hana.ondemand.com
    http:
      paths:
      - path: /
        backend:
          serviceName: xxx-service
          servicePort: 80
