#!/bin/sh

NAME=$1
SCRIPTDIR=$( dirname "${BASH_SOURCE[0]}" )

cat  > "./$SCRIPTDIR/pvc-$NAME.yaml" << EOF
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: $NAME-pvc
  namespace: workshop
spec:
  storageClassName: default
  accessModes:
  -  ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
