#!/bin/sh

NAME=$1
SCRIPTDIR=$( dirname "${BASH_SOURCE[0]}" )


cat  > "./$SCRIPTDIR/easyfit-$NAME.yaml" << EOF
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: workshop
  name: $NAME
spec:
  selector:
    matchLabels:
      app: $NAME
  replicas: 1
  template:
    metadata:
      labels:
        app: $NAME
    spec:
      volumes:
      - name: content-storage
        persistentVolumeClaim:
          claimName: $NAME-pvc
      containers:
      - name: easyfit
        image: c0d1ngm0nk3y/easyfit
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: "/app/FitNesseRoot"
          name: content-storage
---
apiVersion: v1
kind: Service
metadata:
  name: $NAME-service
  namespace: workshop
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: $NAME
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    dns.gardener.cloud/class: garden
    dns.gardener.cloud/dnsnames: all
    nginx.ingress.kubernetes.io/proxy-connect-timeout: 60s
    kubernetes.io/ingress.class: nginx
  name: $NAME-ingress
  namespace: workshop
spec:
  rules:
  - host: tbd
    http:
      paths:
      - backend:
          service:
            name: $NAME-service
            port:
              number: 80
        path: /
        pathType: Prefix
