#!/bin/sh

NAME=$1

cat  > pvc-$NAME.yaml << EOF
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: $NAME-pvc
  namespace: workshop
spec:
  storageClassName: default
  accessModes:
  -  ReadWriteOnce
  resources:
    requests:
      storage: 100M
