#!/bin/sh

NAME=$1
SCRIPTDIR=$( dirname "${BASH_SOURCE[0]}" )


cat  > "./$SCRIPTDIR/easyfit-$NAME.yaml" << EOF
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: workshop
  name: $NAME
spec:
  selector:
    matchLabels:
      app: $NAME
  replicas: 1
  template:
    metadata:
      labels:
        app: $NAME
    spec:
      volumes:
      - name: content-storage
        persistentVolumeClaim:
          claimName: $NAME-pvc
      containers:
      - name: easyfit
        image: c0d1ngm0nk3y/easyfit
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: "/app/FitNesseRoot"
          name: content-storage
---
apiVersion: v1
kind: Service
metadata:
  name: $NAME-service
  namespace: workshop
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: $NAME
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: $NAME-ingress
  namespace: workshop
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: 60s
spec:
  rules:
  - host: $NAME.ingress.k8s.d050893.shoot.canary.k8s-hana.ondemand.com
    http:
      paths:
      - path: /
        backend:
          serviceName: $NAME-service
          servicePort: 80
