---
apiVersion: v1
kind: Namespace
metadata:
  name: workshop
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: workshop
  name: simple-app
spec:
  selector:
    matchLabels:
      app: simple-app
  replicas: 3
  template:
    metadata:
      labels:
        app: simple-app
    spec:
      containers:
      - name: simple-app
        image: c0d1ngm0nk3y/simple-app:v2
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: sut
  namespace: workshop
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: simple-app
  type: ClusterIP
